version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_docker
    ports:
      - "3307:3306" # Mapeia a porta 3307 no host para a 3306 no container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather_app
      MYSQL_USER: root2
      MYSQL_PASSWORD: root2
    volumes:
      - db_data:/var/lib/mysql # Persistência dos dados

volumes:
  db_data:
